Practicing pandas

In [1]:
import pandas as pd

In [4]:
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=['A','B','C'])
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [5]:
df.head()

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [7]:
df.tail(1)

   A  B  C
2  7  8  9

In [8]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [10]:
df.index.tolist()

[0, 1, 2]

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0 bytes